/*
 * generated by Xtext 2.23.0
 */
package tr.edu.itu.ce.demo;


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ProtocolDSlRuntimeModule extends AbstractProtocolDSlRuntimeModule {
}
