/*
 * generated by Xtext 2.23.0
 */
package tr.edu.itu.ce.demo;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ProtocolDSlStandaloneSetup extends ProtocolDSlStandaloneSetupGenerated {

	public static void doSetup() {
		new ProtocolDSlStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
