/*
 * generated by Xtext 2.23.0
 */
package tr.edu.itu.ce.demo.ui.contentassist;


/**
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#content-assist
 * on how to customize the content assistant.
 */
public class ProtocolDSlProposalProvider extends AbstractProtocolDSlProposalProvider {
}
