/*
 * generated by Xtext 2.23.0
 */
package tr.edu.itu.ce.demo.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import tr.edu.itu.ce.demo.ProtocolDSlRuntimeModule;
import tr.edu.itu.ce.demo.ProtocolDSlStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ProtocolDSlIdeSetup extends ProtocolDSlStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ProtocolDSlRuntimeModule(), new ProtocolDSlIdeModule()));
	}
	
}
