/*
 * generated by Xtext 2.23.0
 */
package tr.edu.itu.ce.demo.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ProtocolDSlUiModule extends AbstractProtocolDSlUiModule {

	public ProtocolDSlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
